#include <array>
#include <Windows.h>
#include <string>


std::array<std::pair<std::string, DWORD>, 126> VKEY_NAMES_EN
{
   std::pair<std::string, DWORD>(("NONE"), 0),
   std::pair<std::string, DWORD>(("Left Button"), 0x01),
   std::pair<std::string, DWORD>(("Right Button"), 0x02),
   std::pair<std::string, DWORD>(("CANCEL"), 0x03),
   std::pair<std::string, DWORD>(("Middle Button"), 0x04),
   std::pair<std::string, DWORD>(("Side Button 1"), 0x05),
   std::pair<std::string, DWORD>(("Side Button 2"), 0x06),
   std::pair<std::string, DWORD>(("BACK"), 0x08),
   std::pair<std::string, DWORD>(("TAB"), 0x09),
   std::pair<std::string, DWORD>(("CLEAR"), 0x0C),
   std::pair<std::string, DWORD>(("RETURN"), 0x0D),
   std::pair<std::string, DWORD>(("Shift"), 0x10),
   std::pair<std::string, DWORD>(("Ctrl"), 0x11),
   std::pair<std::string, DWORD>(("Alt"), 0x12),
   std::pair<std::string, DWORD>(("PAUSE"), 0x13),
   std::pair<std::string, DWORD>(("CAPITAL"), 0x14),
  // std::pair<std::string, DWORD>(("KANA"), 0x15),
   //std::pair<std::string, DWORD>(("HANGUEL"), 0x15),
   //std::pair<std::string, DWORD>(("HANGUL"), 0x15),
   std::pair<std::string, DWORD>(("JUNJA"), 0x17),
   std::pair<std::string, DWORD>(("FINAL"), 0x18),
   //std::pair<std::string, DWORD>(("HANJA"), 0x19),
   //std::pair<std::string, DWORD>(("KANJI"), 0x19),
   std::pair<std::string, DWORD>(("ESCAPE"), 0x1B),
   std::pair<std::string, DWORD>(("CONVERT"), 0x1C),
   std::pair<std::string, DWORD>(("NONCONVERT"), 0x1D),
   std::pair<std::string, DWORD>(("ACCEPT"), 0x1E),
   std::pair<std::string, DWORD>(("MODECHANGE"), 0x1F),
   std::pair<std::string, DWORD>(("SPACE"), 0x20),
   std::pair<std::string, DWORD>(("PAGE UP"), 0x21),
   std::pair<std::string, DWORD>(("PAGE DOWN"), 0x22),
   std::pair<std::string, DWORD>(("END"), 0x23),
   std::pair<std::string, DWORD>(("HOME"), 0x24),
   std::pair<std::string, DWORD>(("LEFT"), 0x25),
   std::pair<std::string, DWORD>(("UP"), 0x26),
   std::pair<std::string, DWORD>(("RIGHT"), 0x27),
   std::pair<std::string, DWORD>(("DOWN"), 0x28),
   std::pair<std::string, DWORD>(("SELECT"), 0x29),

   std::pair<std::string, DWORD>(("PRINT"), 0x2A),
   std::pair<std::string, DWORD>(("EXECUTE"), 0x2B),
   std::pair<std::string, DWORD>(("SNAPSHOT"), 0x2C),
   std::pair<std::string, DWORD>(("INSERT"), 0x2D),
   std::pair<std::string, DWORD>(("DELETE"), 0x2E),
   std::pair<std::string, DWORD>(("HELP"), 0x2F),
   std::pair<std::string, DWORD>(("0"), 0x30),
   std::pair<std::string, DWORD>(("1"), 0x31),
   std::pair<std::string, DWORD>(("2"), 0x32),
   std::pair<std::string, DWORD>(("3"), 0x33),
   std::pair<std::string, DWORD>(("4"), 0x34),
   std::pair<std::string, DWORD>(("5"), 0x35),
   std::pair<std::string, DWORD>(("6"), 0x36),
   std::pair<std::string, DWORD>(("7"), 0x37),
   std::pair<std::string, DWORD>(("8"), 0x38),
   std::pair<std::string, DWORD>(("9"), 0x39),
   std::pair<std::string, DWORD>(("A"), 0x41),
   std::pair<std::string, DWORD>(("B"), 0x42),
   std::pair<std::string, DWORD>(("C"), 0x43),
   std::pair<std::string, DWORD>(("D"), 0x44),
   std::pair<std::string, DWORD>(("E"), 0x45),
   std::pair<std::string, DWORD>(("F"), 0x46),
   std::pair<std::string, DWORD>(("G"), 0x47),
   std::pair<std::string, DWORD>(("H"), 0x48),
   std::pair<std::string, DWORD>(("I"), 0x49),
   std::pair<std::string, DWORD>(("J"), 0x4A),
   std::pair<std::string, DWORD>(("K"), 0x4B),
   std::pair<std::string, DWORD>(("L"), 0x4C),
   std::pair<std::string, DWORD>(("M"), 0x4D),
   std::pair<std::string, DWORD>(("N"), 0x4E),
   std::pair<std::string, DWORD>(("O"), 0x4F),
   std::pair<std::string, DWORD>(("P"), 0x50),
   std::pair<std::string, DWORD>(("Q"), 0x51),
   std::pair<std::string, DWORD>(("R"), 0x52),
   std::pair<std::string, DWORD>(("S"), 0x53),
   std::pair<std::string, DWORD>(("T"), 0x54),
   std::pair<std::string, DWORD>(("U"), 0x55),
   std::pair<std::string, DWORD>(("V"), 0x56),
   std::pair<std::string, DWORD>(("W"), 0x57),
   std::pair<std::string, DWORD>(("X"), 0x58),
   std::pair<std::string, DWORD>(("Y"), 0x59),
   std::pair<std::string, DWORD>(("Z"), 0x5A),
   std::pair<std::string, DWORD>(("NUMPAD0"), 0x60),
   std::pair<std::string, DWORD>(("NUMPAD1"), 0x61),
   std::pair<std::string, DWORD>(("NUMPAD2"), 0x62),
   std::pair<std::string, DWORD>(("NUMPAD3"), 0x63),
   std::pair<std::string, DWORD>(("NUMPAD4"), 0x64),
   std::pair<std::string, DWORD>(("NUMPAD5"), 0x65),
   std::pair<std::string, DWORD>(("NUMPAD6"), 0x66),
   std::pair<std::string, DWORD>(("NUMPAD7"), 0x67),
   std::pair<std::string, DWORD>(("NUMPAD8"), 0x68),
   std::pair<std::string, DWORD>(("NUMPAD9"), 0x69),
   std::pair<std::string, DWORD>(("MULTIPLY"), 0x6A),
   std::pair<std::string, DWORD>(("ADD"), 0x6B),
   std::pair<std::string, DWORD>(("SEPARATOR"), 0x6C),
   std::pair<std::string, DWORD>(("SUBTRACT"), 0x6D),
   std::pair<std::string, DWORD>(("DECIMAL"), 0x6E),
   std::pair<std::string, DWORD>(("DIVIDE"), 0x6F),
   std::pair<std::string, DWORD>(("F1"), 0x70),
   std::pair<std::string, DWORD>(("F2"), 0x71),
   std::pair<std::string, DWORD>(("F3"), 0x72),
   std::pair<std::string, DWORD>(("F4"), 0x73),
   std::pair<std::string, DWORD>(("F5"), 0x74),
   std::pair<std::string, DWORD>(("F6"), 0x75),
   std::pair<std::string, DWORD>(("F7"), 0x76),
   std::pair<std::string, DWORD>(("F8"), 0x77),
   std::pair<std::string, DWORD>(("F9"), 0x78),
   std::pair<std::string, DWORD>(("F10"), 0x79),
   std::pair<std::string, DWORD>(("F11"), 0x7A),
   std::pair<std::string, DWORD>(("F12"), 0x7B),
   std::pair<std::string, DWORD>(("F13"), 0x7C),
   std::pair<std::string, DWORD>(("F14"), 0x7D),
   std::pair<std::string, DWORD>(("F15"), 0x7E),
   std::pair<std::string, DWORD>(("F16"), 0x7F),
   std::pair<std::string, DWORD>(("F17"), 0x80),
   std::pair<std::string, DWORD>(("F18"), 0x81),
   std::pair<std::string, DWORD>(("F19"), 0x82),
   std::pair<std::string, DWORD>(("F20"), 0x83),
   std::pair<std::string, DWORD>(("F21"), 0x84),
   std::pair<std::string, DWORD>(("F22"), 0x85),
   std::pair<std::string, DWORD>(("F23"), 0x86),
   std::pair<std::string, DWORD>(("F24"), 0x87),
   std::pair<std::string, DWORD>(("NUMLOCK"), 0x90),
   std::pair<std::string, DWORD>(("SCROLL"), 0x91),
   std::pair<std::string, DWORD>(("Left Shift"), 0xA0),
   std::pair<std::string, DWORD>(("Right Shift"), 0xA1),
   std::pair<std::string, DWORD>(("Left Ctrl"), 0xA2),
   std::pair<std::string, DWORD>(("Right Ctrl"), 0xA3)
};

char* VK2string(int VK)
{

	auto it3 = std::find_if(VKEY_NAMES_EN.begin(), VKEY_NAMES_EN.end(), [&](::std::pair<std::string, DWORD>& p) {
		return p.second == VK; });
	if (it3 != VKEY_NAMES_EN.end())
	{
		char* c = (char*)it3->first.c_str();
		return c;
	}

	return NULL;
}